### PR TITLE
Tweak DynamoDb table update logic and connection secret keys

### LINKED ISSUE #580: Dynamodb writeConnectionSecretToRef does not write secret data
### What happened?

Creaded Dynamobd with
```yaml
    reason: Available
    status: "True"
    type: Ready

    reason: ReconcileSuccess
    status: "True"
    type: Synced
```
but no connection string written to the writeConnectionSecretToRef secret. Its created with no data?

Secret (redacted) :
```yaml
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2021-03-05T03:26:00Z"
  name: dynamodb-my-db
  ownerReferences:
  - apiVersion: dynamodb.aws.crossplane.io/v1alpha1
    controller: true
    kind: Table
type: connection.crossplane.io/v1alpha1
```

### How can we reproduce it?

```yaml
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
#...#
  forProvider:
    attributeDefinitions:
    - attributeName: attribute1
      attributeType: S
    keySchema:
    - attributeName: attribute1
      keyType: HASH
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
    region: ap-southeast-2
    streamSpecification:
      streamEnabled: true
      streamViewType: NEW_AND_OLD_IMAGES
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: dynamodb-my-db
    namespace: #...#
```

### What environment did it happen in?
Crossplane version: v0.17.0

### LINKED ISSUE #637: DynamoDB Table issue with billingMode PAY_PER_REQUEST
### What happened?
While option for Table with option of billingmode PAY_PER_REQUEST

Did encounter error during reconciliation but actual table created

### How can we reproduce it?
Create Table with following manifest

```
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: test-table-ppr
spec:
  forProvider:
    region: us-west-1
    attributeDefinitions:
      - attributeName: attribute1
        attributeType: S
    billingMode: PAY_PER_REQUEST
    keySchema:
      - attributeName: attribute1
        keyType: HASH
  providerConfigRef:
    name: aws-provider
```

Error:
```
conditions:
  - lastTransitionTime: "2021-04-23T02:38:01Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-04-23T02:38:01Z"
    message: 'update failed: pre-update failed: only provisionedThroughput and streamSpecification
      updates are supported'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### What environment did it happen in?
Crossplane version: v1.1
Provider: v0.17.0

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

Fixes #580 (some more)
Fixes #637

This PR follows on from #839. which recently fixed the DynamoDB table controller such that it was possible to configure PAY_PER_REQUEST and SSE, but part of doing this involved potentially making a no-op update and ignoring the resulting error. This commit avoids the no-op update by (hopefully) improving the logic that determines which update(s) are needed.

It also switches the connection details from `PascalCase` to `camelCase`. This isn't codified anywhere but `camelCase` is more idiomatic. Note that this shouldn't be a breaking change because the `PascalCase` connection details were never included in a release.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

I've tested using the examples added in #839. I've also checked that I can:

* Update the billing mode after creation.
* Update (enable) SSE after creation.
* Update provisioned writes after creation.
* Update both SSE and provisioned writes after creation, and that they happen in two subsequent updates.

### CODE REVIEW

File: pkg/controller/dynamodb/table/hooks.go [hunk 1]
```diff
@@ -177,18 +174,18 @@ func lateInitialize(in *svcapitypes.TableParameters, t *svcsdk.DescribeTableOutp
...
+	if t.Table.SSEDescription != nil {
+		if in.SSESpecification == nil {
+			in.SSESpecification = &svcapitypes.SSESpecification{}
+		}
+		if in.SSESpecification.Enabled == nil && t.Table.SSEDescription.Status != nil {
+			in.SSESpecification.Enabled = aws.Bool(*t.Table.SSEDescription.Status == string(svcapitypes.SSEStatus_ENABLED))
 		}
-	}
-	if in.SSESpecification != nil {
 		if in.SSESpecification.KMSMasterKeyID == nil && t.Table.SSEDescription.KMSMasterKeyArn != nil {
```
Comment (negz) [inline pkg/controller/dynamodb/table/hooks.go:184]: I'm pretty sure this refactoring fixes an NPE we had in master that no one hit (at least until I was testing this out). It was possible that:

* `in.SSESpecification` was not nil.
* `in.SSESpecification.KMSMasterKeyID` was nil.
* `t.Table.SSEDescription` was nil

This would happen if (for example) someone was trying to enable SSE by just setting `enabled = true` without including an ARN.

**Review by turkenh — APPROVED** [review]
lgtm!

File: pkg/controller/dynamodb/table/hooks.go [hunk 2]
```diff
@@ -302,59 +318,55 @@ type updateClient struct {
...
-		(aws.StringValue(t.Table.SSEDescription.SSEType) == aws.StringValue(cr.Spec.ForProvider.SSESpecification.SSEType)):
-		newUpdateObj.SSESpecification = u.SSESpecification
 
-	case cr.Spec.ForProvider.BillingMode != nil &&
-		cr.Spec.ForProvider.BillingMode != t.Table.BillingModeSummary.BillingMode:
-		newUpdateObj.BillingMode = u.BillingMode
-
-		// TODO(muvaf): ReplicationGroupUpdate and GlobalSecondaryIndexUpdate features
-		// are not implemented yet.
+	// TODO(muvaf): Implement ReplicaUpdates and GlobalSecondaryIndexUpdates.
```
Comment (jbw976) [inline pkg/controller/dynamodb/table/hooks.go:347]: is this already tracked in an issue, or does it need to be tracked?

File: pkg/controller/dynamodb/table/hooks.go [hunk 3]
```diff
@@ -302,59 +318,55 @@ type updateClient struct {
...
-	switch aws.StringValue(cr.Status.AtProvider.TableStatus) {
-	case string(svcapitypes.TableStatus_SDK_UPDATING), string(svcapitypes.TableStatus_SDK_CREATING):
-		return nil
-	}
-	t, err := e.client.DescribeTable(&svcsdk.DescribeTableInput{TableName: aws.String(meta.GetExternalName(cr))})
+func (e *updateClient) preUpdate(ctx context.Context, cr *svcapitypes.Table, u *svcsdk.UpdateTableInput) error {
+
+	filtered := &svcsdk.UpdateTableInput{TableName: aws.String(meta.GetExternalName(cr))}
+
+	// The AWS API requires us to do one kind of update at a time per
```
Comment (jbw976) [inline pkg/controller/dynamodb/table/hooks.go:325]: that's kind of crazy that the AWS API behaves this way - I hope we don't see that too often because this logic is quite manual and probably difficult to generate :)

**Review by jbw976 — APPROVED** [review]
Are there obvious test cases that should be added for this too?
