### PR TITLE
Fix for 558, only send vpc attributes if set

### LINKED ISSUE #558: Basic VPC creation failed to sync "CannotUpdateExternalResource" / ReconcileError
### What happened?

Creation of a basic VPC leads to a 'Ready' but 'Synced' = False status.
When I look at the description of my VPC resource in kubernetes, I see a lot of :
```
Warning  CannotUpdateExternalResource  18m  managed/vpc.ec2.aws.crossplane.io  failed to modify the VPC resource attributes: InvalidParameterCombination: No attributes specified.
           status code: 400, request id: c4fcc49d-c347-43fc-9e36-3b678db0f4d7
  Warning  CannotUpdateExternalResource  18m  managed/vpc.ec2.aws.crossplane.io  failed to modify the VPC resource attributes: InvalidParameterCombination: No attributes specified.
           status code: 400, request id: f01fd688-4f30-44f4-ad44-c3df826ace54
  Warning  CannotUpdateExternalResource  18m  managed/vpc.ec2.aws.crossplane.io  failed to modify the VPC resource attributes: InvalidParameterCombination: No attributes specified.
           status code: 400, request id: c027ed7e-0fda-4f7c-82d3-b25fcdacb835
  Warning  CannotUpdateExternalResource  18m  managed/vpc.ec2.aws.crossplane.io  failed to modify the VPC resource attributes: InvalidParameterCombination: No attributes specified.
```

### How can we reproduce it?

````sh
cat <<EOF >> vpc.yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: crossplane-vpc-failed
spec:
  forProvider:
    region: eu-west-3
    cidrBlock: 10.0.0.0/16
EOF
kubectl apply -f vpc.yaml 
````

### What environment did it happen in?
Crossplane version: 1.0.0
AWS Provider version: crossplane/provider-aws:v0.16.0
Kubernetes version: v1.20.0
Environment: minikube on MacOS

#### Empty request to AWS

On the AWS side, I see Crossplane tries to call ec2.ModifyVpcAttribute without specifying any attribute.
The `requestParameters` only indicates a `vpcId`, nothing else.

#### Everything's fine with non-default values

I succeed to create a VPC if I indicate all the optional fields:
````sh
cat <<EOF >> vpc-ok.yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: crossplane-vpc-ok
spec:
  forProvider:
    region: eu-west-3
    cidrBlock: 10.0.0.0/16
    enableDnsHostNames: true
    enableDnsSupport: true
    instanceTenancy: default
    tags:
    - key: Name
      value: crossplane-vpc-ok
EOF
kubectl apply -f vpc-ok.yaml 
````

### PR DESCRIPTION
**Pull request by enderv**
Signed-off-by: chris <cvodak@ea.com>

### Description of your changes

Fixes #558 Only send vpc attributes if set. Also added lateInitialization as EnableDnsSupport has a default of true if not set.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Ran and added to unit tests. Created a test vpc setting neither enableDnsHostNames or  enableDnsSupport of the values in the issue. Modified the vpc changing values to ensure they were updated in aws correctly.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/controller/ec2/vpc/controller.go [hunk 1]
```diff
@@ -191,17 +192,22 @@ func (e *external) Update(ctx context.Context, mgd resource.Managed) (managed.Ex
 		return managed.ExternalUpdate{}, errors.New(errUnexpectedObject)
 	}
 
-	for _, input := range []*awsec2.ModifyVpcAttributeInput{
-		{
+	if cr.Spec.ForProvider.EnableDNSSupport != nil {
```
Comment (hasheddan) [inline pkg/controller/ec2/vpc/controller.go:195]: I don't love that we will make _all_ of these calls if the fields are set even if they don't need to be changed (i.e. the diff was elsewhere in the spec). That being said, this is the current existing pattern (as opposed to getting again, calculating diff, then only making the specific call), so I am fine with moving forward with this fix 👍

**Review by hasheddan — APPROVED** [review]
Thanks so much for fixing this @enderv!

File: pkg/controller/ec2/vpc/controller.go (hunk 1 above)
Comment (cdenneen) [reply pkg/controller/ec2/vpc/controller.go:195]: @hasheddan I think I just ran into a bug here. So in my case I'm importing and existing vpc. I'm using the `crossplane.io/external-name` annotation in order to pull in an existing vpc. In doing so I'm getting an error of:

```
 Message:               update failed: failed to modify the VPC resource attributes: api error UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: 17IZjLqa5Zh3OjVaZ3t9FH0FftiP1SQ3_yRUhVUg42S9N-S5HC6P5UNgad1lXNzm9uEfvQyWMV-JzvjbCbdBoeCDdaAeadxZWWO5F94c-Qm0ba2sMINryty1b1F_wuzxG9Pi_1Mb9QEwuMSjR2zK7Bttkm20YGfP-NKxSIenBSHVCmy5yfW915cTLqakozjE8Dmt2Ml95_XT8nQ5QZj-bYHkCIu5WjTY5VQQNe7Ur7hPXNoj2Zqp3mUnwpJKmPp0XAHgRrQtnClrc_aFldtspgv2Ty97AhgIQtOWHIvX4iadQ1uafOakWfKoONODQaUw8zqHHsBNt6a1-Cy7nQ9Q1weM0tyeVykTioT1iRqq2arbvdvSjWvPq9P8qqpkovXFBqxRExx8wibFiZ6G5bV3lmAv4wMZOa11p0nuisNmnc2xJXDb8gyX2dwSQSXL336pRHgKt4S-VITej52_-o-qD7wqEzmN6rZibbfIA2xwGddtEBX95zwgqJcgWLIr-Rvz4q4ktgLuIJH5G5rOkmH1ZiCMTVswY98WjouXAl9bXUaNnp55LzvhSdNajsW77Uuu5kDlc0A4WAUrdaGD6He8foMacrySqBwyrlJLULa-NxkHcKC5p2tt5i3k-BYurVJswQnqXTIbmH4lwV5GIimXuPkcaGX9lKXhvGUl4zAiYCSmG_QweVQT0cglv8dg9R4oOwws8WNtDM_aHQbDjxO13SO1I17geD1ERFiHqdN7igqbPLs2aRUA7f5vVS7Z-DsF-p5Mf5uke7qv-4eyd7on2bV-e-rDrH5W6KfwoyBLvbq7xZGY7rIG3is9aQgDoBFwk2NVcIAKPlP0OQ2y0OKxx83q_mUcDcpsYdz5ZmZjghiaJr9UMxzEfnuEwTvBwVPqRJiw1CdWhoqmMoIPGg
```

In checking CloudTrail I see it's attempting to do a `ModifyVpcResource` on `enableDnsSupport` even though it's already set. 

Obviously in our case we are using vpc as a ReadOnly resource for reference but it shouldn't try to Modify an attribute if it matches. I've tried setting the forProvider to not set these 2 attributes and it still tries to Modify... I've tried to set these forProvider parameters to match what they currently are on vpc and it still tries to modify.

Comment (cdenneen) [reply pkg/controller/ec2/vpc/controller.go:195]: @hasheddan I think I just ran into a bug here. So in my case I'm importing and existing vpc. I'm using the `crossplane.io/external-name` annotation in order to pull in an existing vpc. In doing so I'm getting an error of:

```
 Message:               update failed: failed to modify the VPC resource attributes: api error UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: 17IZjLqa5Zh3OjVaZ3t9FH0FftiP1SQ3_yRUhVUg42S9N-S5HC6P5UNgad1lXNzm9uEfvQyWMV-JzvjbCbdBoeCDdaAeadxZWWO5F94c-Qm0ba2sMINryty1b1F_wuzxG9Pi_1Mb9QEwuMSjR2zK7Bttkm20YGfP-NKxSIenBSHVCmy5yfW915cTLqakozjE8Dmt2Ml95_XT8nQ5QZj-bYHkCIu5WjTY5VQQNe7Ur7hPXNoj2Zqp3mUnwpJKmPp0XAHgRrQtnClrc_aFldtspgv2Ty97AhgIQtOWHIvX4iadQ1uafOakWfKoONODQaUw8zqHHsBNt6a1-Cy7nQ9Q1weM0tyeVykTioT1iRqq2arbvdvSjWvPq9P8qqpkovXFBqxRExx8wibFiZ6G5bV3lmAv4wMZOa11p0nuisNmnc2xJXDb8gyX2dwSQSXL336pRHgKt4S-VITej52_-o-qD7wqEzmN6rZibbfIA2xwGddtEBX95zwgqJcgWLIr-Rvz4q4ktgLuIJH5G5rOkmH1ZiCMTVswY98WjouXAl9bXUaNnp55LzvhSdNajsW77Uuu5kDlc0A4WAUrdaGD6He8foMacrySqBwyrlJLULa-NxkHcKC5p2tt5i3k-BYurVJswQnqXTIbmH4lwV5GIimXuPkcaGX9lKXhvGUl4zAiYCSmG_QweVQT0cglv8dg9R4oOwws8WNtDM_aHQbDjxO13SO1I17geD1ERFiHqdN7igqbPLs2aRUA7f5vVS7Z-DsF-p5Mf5uke7qv-4eyd7on2bV-e-rDrH5W6KfwoyBLvbq7xZGY7rIG3is9aQgDoBFwk2NVcIAKPlP0OQ2y0OKxx83q_mUcDcpsYdz5ZmZjghiaJr9UMxzEfnuEwTvBwVPqRJiw1CdWhoqmMoIPGg
```

In checking CloudTrail I see it's attempting to do a `ModifyVpcResource` on `enableDnsSupport` even though it's already set. 

Obviously in our case we are using vpc as a ReadOnly resource for reference but it shouldn't try to Modify an attribute if it matches. I've tried setting the forProvider to not set these 2 attributes and it still tries to Modify... I've tried to set these forProvider parameters to match what they currently are on vpc and it still tries to modify.
