### PR TITLE
fix(hostedzone): fix DelegationSet.id can be nil panic

### LINKED ISSUE #797: Panic when empty/missing DelegationSet returned from Route53 HostedZone
### What happened?

I created a `hostedzones.route53.aws.crossplane.io`, which successfully creates the AWS resource (`Synced`=true), but the provider then crash-loops, and my objects are never marked as Ready.

Looking at the [line in question](https://github.com/crossplane/provider-aws/blob/master/pkg/clients/hostedzone/hostedzone.go#L71), it seems to be a result of the observed `DelegationSet` being empty.

```
     1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1788 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x28a5580, 0x51038a0)
    /home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x28a5580, 0x51038a0)
    /opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:969 +0x166
github.com/crossplane/provider-aws/pkg/clients/hostedzone.LateInitialize(0xc00169a380, 0xc000ec0be0)
    /home/runner/work/provider-aws/provider-aws/pkg/clients/hostedzone/hostedzone.go:71 +0x49
github.com/crossplane/provider-aws/pkg/controller/route53/hostedzone.(*external).Observe(0xc001739ee0, 0x34e69c0, 0xc0016a4900, 0x353fd40, 0xc00169a240, 0x34e7d00, 0xc001739ee0, 0x0, 0x0)
    /home/runner/work/provider-aws/provider-aws/pkg/controller/route53/hostedzone/controller.go:113 +0x376
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc00046f680, 0x34e6a00, 0xc000c81e30, 0x0, 0x0, 0xc001725860, 0x18, 0xc000c81e00, 0x0, 0x0, ...)
    /home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:614 +0x1d58
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00046f720, 0x34e6940, 0xc000814000, 0x29c8b40, 0xc000c96f20)
    /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:293 +0x2f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00046f720, 0x34e6940, 0xc000814000, 0x0)
    /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:248 +0x202
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x34e6940, 0xc000814000)
    /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
    /home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000fae750)
    /home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000cdff50, 0x34872c0, 0xc000c81dd0, 0xc000814001, 0xc0000d81e0)
    /home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000fae750, 0x3b9aca00, 0x0, 0x1, 0xc0000d81e0)
    /home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x34e6940, 0xc000814000, 0xc0016f4520, 0x3b9aca00, 0x0, 0x1)
    /home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x34e6940, 0xc000814000, 0xc0016f4520, 0x3b9aca00)
    /home/runner/work/provider-aws/provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
    /home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:208 +0x4f9
```

### How can we reproduce it?

I hope this helps: the spec of our Zone, and the status:

```yaml
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: HostedZone
metadata:
  annotations:
    crossplane.io/external-name: Z02972861XN6W0EFFL9HE
  creationTimestamp: "2021-08-09T21:34:21Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: abc-com-r7k72-
  generation: 2
  labels:
    crossplane.io/claim-name: abc-com
    crossplane.io/claim-namespace: devt-us
    crossplane.io/composite: abc-com-r7k72
  name: abc-com-r7k72-ggtpm
  ownerReferences:
  - apiVersion: aws.abc.com/v1alpha1
    controller: true
    kind: CompositeDnsZone
    name: abc-com-r7k72
    uid: ddc997cf-4356-4a36-8357-2a26ebdee7dd
  resourceVersion: "4164119"
  uid: 24596421-d53e-48d9-b605-149c495afa14

spec:
  deletionPolicy: Delete
  forProvider:
    config:
      comment: Internal zone
      privateZone: true
    name: abc.com
    vpc:
      vpcId: vpc-04a2dd28a14f3c813
      vpcIdRef:
        name: devt-us-lwzjx-5n499
      vpcIdSelector:
        matchLabels:
          networks.aws.abc.com/network-id: devt-us
      vpcRegion: us-west-1
  providerConfigRef:
    name: devt-us
status:
  atProvider:
    delegationSet: {}
    hostedZone:
      linkedService: {}
  conditions:
  - lastTransitionTime: "2021-08-09T21:34:22Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```

If I GET the zone directly via the AWS API, there's no DelegationSet:

`aws route53 get-hosted-zone --id Z02972861XN6W0EFFL9HE --profile devt-us`

```json
{
    "HostedZone": {
        "Id": "/hostedzone/Z10299403D80T5TI2QEYY",
        "Name": "abc.com.",
        "CallerReference": "4031604",
        "Config": {
            "Comment": "Internal zone",
            "PrivateZone": true
        },
        "ResourceRecordSetCount": 2
    },
    "VPCs": [
        {
            "VPCRegion": "us-west-1",
            "VPCId": "vpc-xxxxxxx"
        }
    ]
}
```

### What environment did it happen in?

Crossplane version: 1.3.0
provider-aws-controller: v0.19.0
EKS v1.21.2-eks-0389ca3

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: Christopher Haar <chhaar30@googlemail.com>

### Description of your changes
obs.DelegationSet.Id  status is nil for example for privateHostedZones - added check

Fixes #797

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

create hostedZone without error in provider-aws

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/clients/hostedzone/hostedzone.go [hunk 1]
```diff
@@ -68,7 +68,9 @@ func LateInitialize(spec *v1alpha1.HostedZoneParameters, obs *route53.GetHostedZ
 	if obs == nil || obs.HostedZone == nil {
 		return
 	}
-	spec.DelegationSetID = awsclients.LateInitializeStringPtr(spec.DelegationSetID, obs.DelegationSet.Id)
+	if spec.DelegationSetID == nil && obs.DelegationSet.Id != nil {
```
Comment (chlunde) [inline pkg/clients/hostedzone/hostedzone.go:71]: Did you manage to reproduce the panic? I suspect `obs.DelegationSet` is the nil-check we need, as @poblish mentions.

* `spec.DelegationSetID == nil` is checked by `LateInitializeStringPtr`
* `obs.DelegationSet.Id == nil` would be a noop, we would only assign that `nil` to `spec.DelegationSetID` in the case where it is already `nil`, due to the guard above.

Either way, unless `obs.DelegationSet` is `nil` I fail to see how this could panic.

So I wonder if the correct fix is:

```suggestion
	if obs.DelegationSet != nil {
```

Comment (haarchri) [reply pkg/clients/hostedzone/hostedzone.go]: yes - reproduce with private hosted dns zone - i checked your suggestion lgtm i changed my pr
thanks for review

**Review by chlunde — APPROVED** [review]

**Comment by haarchri** [comment]
@chlunde is something missing for merging ?

**Comment by chlunde** [comment]
@haarchri I wanted to test it manually, since there's no test and I have not used hostedzone, but I think it's safe to merge, so I'll do it now :smile:
