### PR TITLE
routetable: do not issue status update before create 

### LINKED ISSUE #392: Routetable controller can lose track of created external resource
### What happened?

In some cases, creation of `RouteTable` succeeds but its ID cannot be written to spec when [this call](https://github.com/crossplane/provider-aws/blob/c0bacda/pkg/controller/ec2/routetable/controller.go#L185) returns error. As an example:
```
Events:
  Type     Reason                           Age                    From                                      Message
  ----     ------                           ----                   ----                                      -------
  Warning  CannotResolveResourceReferences  5m52s (x3 over 5m54s)  managed/routetable.ec2.aws.crossplane.io  cannot resolve references: spec.forProvider.vpcId: referenced field was empty (referenced resource may not yet be ready)
  Warning  CannotResolveResourceReferences  5m22s (x2 over 5m22s)  managed/routetable.ec2.aws.crossplane.io  cannot resolve references: spec.forProvider.routes[0].gatewayId: referenced field was empty (referenced resource may not yet be ready)
  Warning  CannotCreateExternalResource     4m51s                  managed/routetable.ec2.aws.crossplane.io  cannot update spec of the RouteTable custom resource: Operation cannot be fulfilled on routetables.ec2.aws.crossplane.io "network-smzhg-j2vvc": the object has been modified; please apply your changes to the latest version and try again
  Normal   CreatedExternalResource          4m49s                  managed/routetable.ec2.aws.crossplane.io  Successfully requested creation of external resource
  Normal   UpdatedExternalResource          39s (x20 over 4m47s)   managed/routetable.ec2.aws.crossplane.io  Successfully requested update of external resource
```

As you can see, the first `CannotCreateExternalResource` event says update failed, which means the ID wasn't saved and in the reconcile a new one is created and its ID is successfully stored.

The tricky part is it doesn't always happen because the error says the object is not up-to-date, however, we update it right before the `CreateRouteTableRequest` call via `kube.Status().Update`. It seems like in some cases (api-server too busy, etcd slowness etc.), this status update call doesn't get the most up-to-date object from the server so we end up in a local variable `cr` that is old to be used for an update.

### How can we reproduce it?

Create `RouteTable` objects in a constrained.

### What environment did it happen in?
Crossplane version: 0.13.0
AWS: 83bf642

### PR DESCRIPTION
**Pull request by muvaf**
### Description of your changes

Because the object returned by the api-server may not be latest, hence, causing spec update to fail which in turn creates additional routetable whose track is lost.

Keep in mind that this should not happen as status update already updates the local `cr` variable. However, we see this happening in some environments.

The actual solution to this problem is to have `Create` operations whose result has to be saved to be atomic, i.e. if spec update didn't go through then delete the created external resource.

Fixes #392
Fixes https://github.com/crossplane/provider-aws/issues/210
Fixes https://github.com/upbound/platform-ref-aws/issues/3

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Manually.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/controller/ec2/routetable/controller.go [hunk 1]
```diff
@@ -162,26 +161,16 @@ func (e *external) Create(ctx context.Context, mgd resource.Managed) (managed.Ex
 	if !ok {
 		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
 	}
-
-	cr.Status.SetConditions(runtimev1alpha1.Creating())
-	if err := e.kube.Status().Update(ctx, cr); err != nil {
-		return managed.ExternalCreation{}, errors.Wrap(err, errStatusUpdate)
-	}
```
Comment (hasheddan) [inline pkg/controller/ec2/routetable/controller.go:169]: @muvaf just want to check and make sure I am understanding this correctly --> this status update is bumping resource version, which is causing our `meta.SetExternalName` update to fail, meaning we try to `Create` again on next reconcile and end up with two Route Tables?

Comment (muvaf) [reply pkg/controller/ec2/routetable/controller.go:169]: No, if status update works as expected, there is no problem because the local `cr` object would be updated to reflect the latest state and the next statements would work on the latest object, hence no error. However, api-server doesn't always return the updated object in that call for some reason that could be low limit, too busy or slow etcd.

Comment (hasheddan) [reply pkg/controller/ec2/routetable/controller.go:169]: So we get a successful update but the returned object is not latest?

Comment (muvaf) [reply pkg/controller/ec2/routetable/controller.go:169]: For example, this problem happens in a constrained UbC environment 50% of the time.

**Review by hasheddan — APPROVED** [review]
Noting here that we investigated further and think the likely issue is actually that the status update here is triggering the composition controller and so the resource version gets bumped between our status and spec updates, causing the failing spec update (and thus the double route table creation). This is just a partial fix to make this scenario less likely, but doesn't eliminate this problem, and this will need to be addressed further. Thanks for working on this @muvaf!
