### PR TITLE
security group: remove the default egress and fix comparison issue

### LINKED ISSUE #296: SecurityGroups never finish creating
### What happened?
SecurityGroups never finish. The status Ready is always false. I have waited for quite some time and it does not seem to change. 

### How can we reproduce it?
Try this out:
```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: foo-tester
spec:
  forProvider:
    description: A test sg to see if it can finish
    egress:
    - fromPort: -1
      ipProtocol: "-1"
      ipRanges:
      - cidrIp: 0.0.0.0/0
        description: Any IP address.
      toPort: -1
    groupName: foo-tester
    ingress:
    - fromPort: 6379
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 10.101.0.0/16
        description: Just the cidr from the vpc only.
      toPort: 6379
    vpcIdRef:
      name: my-vpc
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
```

### What environment did it happen in?
Crossplane version: 0.12.0
Provider-aws: 0.11.0

### PR DESCRIPTION
**Pull request by muvaf**
### Description of your changes

`SecurityGroup` creates an inital egress rule and if user's egress rule corresponds to this existing one, no change is propagated such as description so it always returned that the resource is not up-to-date. Additionally, `-1` value for `fromPort` and `toPort` is special for AWS and they return `nil` for values of those fields if you had submitted `-1` and that'd cause not up-to-date error since spec has `-1` but observed value seems to be `nil`.

Manually tested.

Fixes #296 

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation], [examples], or [release notes].
- [x] Updated the dependencies in [`app.yaml`] to include any new role permissions.

[documentation]: https://github.com/crossplane/crossplane/tree/master/docs
[examples]: https://github.com/crossplane/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplane/crossplane/tree/master/PendingReleaseNotes.md
[`app.yaml`]: https://github.com/crossplane/provider-aws/blob/master/config/package/manifests/app.yaml

### CODE REVIEW

File: pkg/clients/ec2/securitygroup.go [hunk 1]
```diff
@@ -149,6 +151,24 @@ func CreateSGPatch(in ec2.SecurityGroup, target v1beta1.SecurityGroupParameters)
 	v1beta1.SortTags(target.Tags, in.Tags)
 	LateInitializeSG(currentParams, &in)
 
+	// NOTE(muvaf): Sending -1 is sent as FromPort or ToPort is valid but the
```
Comment (hasheddan) [inline pkg/clients/ec2/securitygroup.go:154]:
```suggestion
	// NOTE(muvaf): Sending -1 as FromPort or ToPort is valid but the
```

File: pkg/controller/ec2/securitygroup/controller.go [hunk 2]
```diff
@@ -185,18 +186,29 @@ func (e *external) Create(ctx context.Context, mgd resource.Managed) (managed.Ex
...
 	}
-
 	meta.SetExternalName(cr, aws.StringValue(result.GroupId))
 
-	return managed.ExternalCreation{}, errors.Wrap(e.kube.Update(ctx, cr), errSpecUpdate)
+	if err := e.kube.Update(ctx, cr); err != nil {
+		return managed.ExternalCreation{}, errors.Wrap(err, errSpecUpdate)
+	}
+	// NOTE(muvaf): AWS creates an initial egress rule and there is no way to
+	// disable it with the create call. So, we revoke it right after the creation.
```
Comment (hasheddan) [inline pkg/controller/ec2/securitygroup/controller.go:201]: Should we always revoke? If the user supplies no egress rules should we assume they want the default?

Comment (muvaf) [reply pkg/controller/ec2/securitygroup/controller.go:201]: I think so. The CR is supposed to serve as the source of truth. In other cases, we'd cover that in late-init but when user does give an entry in that array the default one is not late-inited so we get into a loop of up-to-date.

Also in AWS console, that rule is populated in creation options and when you remove it and click create, you see revoke call being made in the progress bar.

Comment (hasheddan) [reply pkg/controller/ec2/securitygroup/controller.go:201]: Nice! This sounds like a reasonable solution here, thanks for explaining :)
