### PR TITLE
fix(transfer/user): fix WithInitializers and removed postCreate

### LINKED ISSUE #1102: Transfer User can not be created: Missing username
### What happened?

The username was set to use the external name annotation in #1053. However, the annotation is only set after the successful creation of the user and no available in the preCreate hook. 

https://github.com/crossplane/provider-aws/blob/master/pkg/controller/transfer/user/setup.go#L98
https://github.com/crossplane/provider-aws/blob/master/pkg/controller/transfer/user/setup.go#L91

### How can we reproduce it?

Apply the example resource https://github.com/crossplane/provider-aws/blob/master/examples/transfer/user.yaml

### What environment did it happen in?
provider-aws:v0.23

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: haarchri <chhaar30@googlemail.com>

### Description of your changes
set correct `managed.WithInitializers` missed a local commit in #1053 sorry

Fixes #1102

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

```
kubectl get users.transfer
NAME      READY   SYNCED   EXTERNAL-NAME
example   True    True     example
```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/controller/transfer/user/setup.go [hunk 1]
```diff
@@ -84,14 +83,6 @@ func postObserve(_ context.Context, cr *svcapitypes.User, obj *svcsdk.DescribeUs
...
-	if err != nil {
-		return managed.ExternalCreation{}, err
-	}
-	meta.SetExternalName(cr, awsclients.StringValue(obj.UserName))
-	return managed.ExternalCreation{}, nil
-}
-
 func preCreate(_ context.Context, cr *svcapitypes.User, obj *svcsdk.CreateUserInput) error {
 	obj.ServerId = cr.Spec.ForProvider.ServerID
 	obj.Role = cr.Spec.ForProvider.Role
```
Comment (muvaf) [inline pkg/controller/transfer/user/setup.go:88]: I wonder how that worked out before when nothing set the external name annotation

**Review by muvaf — APPROVED** [review]
Thanks!
