### PR TITLE
fix(Cloudfront): LateInit missing fields

### LINKED ISSUE #1295: Cloudfront Distribution resource doesn't become ready when ResponseHeadersPolicyID is set
### What happened?

Setting "ResponseHeadersPolicyID" field caused infinite synching. 

### How can we reproduce it?

Can be reproduced with following manifest:
```
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: example-distribution-custom-origin
spec:
  forProvider:
    region: us-east-1
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution
      origins:
        items:
          - domainName: crossplane-example.amazon.com
            id: customOrigin
            customOriginConfig:
              httpPort: 80
              originProtocolPolicy: "http-only"
              originReadTimeout: 10
              originKeepaliveTimeout: 5
              httpSPort: 443
              originSSLProtocols:
                items:
                  - TLSv1
      defaultCacheBehavior:
        responseHeadersPolicyID: <policyID>
        targetOriginID: customOrigin
        viewerProtocolPolicy: allow-all
        minTTL: 0
        forwardedValues:
          cookies:
            forward: none
          queryString: false
```

### What environment did it happen in?
provider-aws version: v0.26.1

### PR DESCRIPTION
**Pull request by ezgidemirel**
Signed-off-by: ezgidemirel <ezgidemirel91@gmail.com>

### Description of your changes

This PR late initializes ResponseHeadersPolicyID and FunctionAssociation fields.  

Fixes #1295 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Created a distribution with ResponseHeadersPolicyID.
```
NAME                                                                              READY   SYNCED   EXTERNAL-NAME
responseheaderspolicy.cloudfront.aws.crossplane.io/ezgi-response-headers-policy   True    True     7cfa4a57-984a-4985-8ea7-4dcdecb9750f
NAME                                                                           READY   SYNCED   EXTERNAL-NAME
distribution.cloudfront.aws.crossplane.io/example-distribution-custom-origin   True    True     E27DGUZ2ZA71OI

```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/controller/cloudfront/distribution/lateinit.go [hunk 1]
```diff
@@ -728,3 +737,50 @@ func lateInitLambdaFunctionAssociation(in *svcapitypes.LambdaFunctionAssociation
...
+			continue
+		}
+
+		lateInitFunctionAssociation(il, fl)
+	}
+}
+
+func lateInitFunctionAssociation(in *svcapitypes.FunctionAssociation, from *svcsdk.FunctionAssociation) {
+	in.EventType = awsclients.LateInitializeStringPtr(in.EventType, from.EventType)
+	in.EventType = awsclients.LateInitializeStringPtr(in.FunctionARN, from.FunctionARN)
```
Comment (ulucinar) [inline pkg/controller/cloudfront/distribution/lateinit.go:785]: Should this be?:
```suggestion
	in.FunctionARN = awsclients.LateInitializeStringPtr(in.FunctionARN, from.FunctionARN)
```

File: pkg/controller/cloudfront/distribution/lateinit.go [hunk 2]
```diff
@@ -728,3 +737,50 @@ func lateInitLambdaFunctionAssociation(in *svcapitypes.LambdaFunctionAssociation
...
+			lateInitFunctionAssociation(in.Items[i], from.Items[i])
+		}
+
+		return
+	}
+
+	// If we have some function associations, we need to late init each one of them
+	existing := make(map[string]*svcsdk.FunctionAssociation)
+	for i := range from.Items {
+		o := from.Items[i]
```
Comment (ulucinar) [inline pkg/controller/cloudfront/distribution/lateinit.go:760]:
```suggestion
	for _, o := range from.Items {
```

File: pkg/controller/cloudfront/distribution/lateinit.go [hunk 3]
```diff
@@ -728,3 +737,50 @@ func lateInitLambdaFunctionAssociation(in *svcapitypes.LambdaFunctionAssociation
...
+		if o.FunctionARN == nil {
+			continue
+		}
+		// FunctionARN must be unique for each FunctionAssociation
+		existing[awsclients.StringValue(o.FunctionARN)] = o
+	}
+
+	for i := range in.Items {
+		il := in.Items[i]
+		if il.FunctionARN == nil {
```
Comment (ulucinar) [inline pkg/controller/cloudfront/distribution/lateinit.go:770]: If `il.FunctionARN` is `nil`, should we skip it or actually late-initialize it (set it to `fl.FunctionARN`)? Doesn't a `nil` value denote an unset value in this context?

File: pkg/controller/cloudfront/distribution/lateinit.go (hunk 2 above)
Comment (ezgidemirel) [reply pkg/controller/cloudfront/distribution/lateinit.go]: done

File: pkg/controller/cloudfront/distribution/lateinit.go [hunk 4]
```diff
@@ -728,3 +737,50 @@ func lateInitLambdaFunctionAssociation(in *svcapitypes.LambdaFunctionAssociation
...
+		o := from.Items[i]
+		if o.FunctionARN == nil {
+			continue
+		}
+		// FunctionARN must be unique for each FunctionAssociation
+		existing[awsclients.StringValue(o.FunctionARN)] = o
+	}
+
+	for i := range in.Items {
+		il := in.Items[i]
```
[the remark this answers is not in the document]
Comment (ezgidemirel) [reply pkg/controller/cloudfront/distribution/lateinit.go]: done

File: pkg/controller/cloudfront/distribution/lateinit.go [hunk 5]
```diff
@@ -728,3 +737,48 @@ func lateInitLambdaFunctionAssociation(in *svcapitypes.LambdaFunctionAssociation
...
+
+		return
+	}
+
+	// If we have some function associations, we need to late init each one of them
+	existing := make(map[string]*svcsdk.FunctionAssociation)
+	for _, o := range from.Items {
+		if o.FunctionARN == nil {
+			continue
+		}
```
Comment (ulucinar) [inline pkg/controller/cloudfront/distribution/lateinit.go:762]: Please see the comment below regarding the chosen key. We would not expect the key type to be a pointer but although in the console UI, it's not a pointer type, the SDK expects a pointer type. We did not check what happens if you call the SDK function with a nil `EventType` but from what we observed from the console UI, this should not be allowed.
```suggestion
```

File: pkg/controller/cloudfront/distribution/lateinit.go [hunk 6]
```diff
@@ -728,3 +737,48 @@ func lateInitLambdaFunctionAssociation(in *svcapitypes.LambdaFunctionAssociation
...
+		// FunctionARN must be unique for each FunctionAssociation
+		existing[awsclients.StringValue(o.FunctionARN)] = o
```
Comment (ulucinar) [inline pkg/controller/cloudfront/distribution/lateinit.go:764]:
```suggestion
		existing[awsclients.StringValue(o.EventType)] = o
```

File: pkg/controller/cloudfront/distribution/lateinit.go [hunk 7]
```diff
@@ -728,3 +737,48 @@ func lateInitLambdaFunctionAssociation(in *svcapitypes.LambdaFunctionAssociation
...
+	}
+
+	for _, il := range in.Items {
+		if il.FunctionARN == nil {
```
Comment (ulucinar) [inline pkg/controller/cloudfront/distribution/lateinit.go:768]:
```suggestion
		if il.EventType != nil {
```

File: pkg/controller/cloudfront/distribution/lateinit.go [hunk 8]
```diff
@@ -728,3 +737,48 @@ func lateInitLambdaFunctionAssociation(in *svcapitypes.LambdaFunctionAssociation
...
+			continue
+		}
+
+		fl := existing[awsclients.StringValue(il.FunctionARN)]
```
Comment (ulucinar) [inline pkg/controller/cloudfront/distribution/lateinit.go:772]:
```suggestion
		fl := existing[awsclients.StringValue(il.EventType)]
```

File: pkg/controller/cloudfront/distribution/lateinit.go (hunk 5 above)
Comment (ezgidemirel) [reply pkg/controller/cloudfront/distribution/lateinit.go]: Removing this nil check caused following error: 
```- lastTransitionTime: "2022-05-11T08:44:05Z"
    message: "update failed: cannot update Distribution in AWS: PreconditionFailed:
      The request failed because it didn't meet the preconditions in one or more request-header
      fields.\n\tstatus code: 412, request id: "
```
I added back with the `EventType`.

File: pkg/controller/cloudfront/distribution/lateinit.go [hunk 9]
```diff
@@ -696,14 +705,14 @@ func lateInitLambdaFunctionAssociations(in *svcapitypes.LambdaFunctionAssociatio
...
 	}
-
 	// If we have some lambda function associations, we need to late init each one of them
 	existing := make(map[string]*svcsdk.LambdaFunctionAssociation)
 	for i := range from.Items {
 		o := from.Items[i]
 		if o.LambdaFunctionARN == nil {
 			continue
 		}
+		// TODO(ezgidemirel): Instead of using FunctionARNs, we should use EventTypes as keys
```
Comment (ulucinar) [inline pkg/controller/cloudfront/distribution/lateinit.go:715]: We may consider opening a bug in the repo.

**Review by ulucinar — APPROVED** [review]
Thank you @ezgidemirel. We may consider opening a separate bug to track the issue spotted for the `LambdaFunctionAssociation`s.
